<?php
  function connectDb($serverName, $userName, $password, $dbName) {
    /*
    Establishes a connection to the specified server and database.
    Inputs;
      serverName:       A string containing the FQDN or IP address of the server to connect to
      userName: A string containing the user name to use for authentication
      password: A string containing the password to use for authentication
      dbName:   A string containing the name of the database to connect to
    Returns/Outputs;
      Success:  A connection resource
      Failure:  Dies and outputs a string beginnging with "ERROR"
    */
    //Check if all required arguments have been specified. If yes continue, if not die and display an error message.
    if (!$serverName || !$userName || !$password || !$dbName) {
      die("ERROR: connect_db: missing arguments");
    } else {
      //Establish a connection to the server.
      $connection = @mysql_connect($serverName, $userName, $password)
        or die("ERROR: connect_db: connection problem:" . mysql_error());
      //Establish a connection to the database.
      mysql_select_db($dbName)
        or die("ERROR: connect_db: db select problem:" . mysql_error());
      return $connection;
    }
  }

  function selectFromTable($tableName, $fieldsSQL, $connection) {
    /*
    Retrieves the specificed fields for all records in the specified table with the specified sorting.
    Inputs;
      tableName:  A string containing the name of the table to query
      connection:  A reference to the connection object to use for the query
    Returns/Outputs;
      Success:  A recordset resource containing the contents of the table
      Failure:  Dies and outputs a string beginnging with "ERROR"
    */
    //Check if all required arguments have been specified. If yes continue, if not die and display an error message.
    if (!$tableName || !$fieldsSQL || !$connection) {
      die("ERROR: select_from_table: missing arguments");
    } else {
      //Build the select query and execute it.
      $selectQuery = 'select ' . $fieldsSQL . ' from ' . $tableName;
      $result = mysql_query($selectQuery, $connection)
        or die("ERROR: select_from_table: select problem:" . mysql_error());
      return $result;
    }
  }

  function recordsetToText($recordSet) {
    /*
    Converts a recordset generated by an SQL select query into a HTML table.
    The recordset may contain any number of columns and rows.
    Inputs;
      recordSet:  A reference to the record set to convert
    Returns/Outputs;
      Success:  A string containing the HTML code for the table
      Failure:  Dies and outputs a string beginnging with "ERROR"
    */
    //Check if all required arguments have been specified. If yes continue, if not die and display an error message.
    if (!$recordSet) {
      die("ERROR: recordset_to_htmltable: missing arguments");
    } else {
      //Set the counter. This is used later to set the first row as headers.
      $counter = 0;
      $textOutput = "";
      //Begin constructing the string which will contain the HTML code for the table. Each new line will be concatenated on to this variable
      //Loop trough the recordset.
      while($row = mysql_fetch_array($recordSet)) {
        //Extract the values and add them to the HTML.
        for($column = 0; $column < count($row)/2; $column++) {
          $textOutput .= $row[$column] . "\n";
        }
        //Increment counter
        $counter += 1;
      }
      return $textOutput;
    }
  }

  $dbConnection = connectDb('localhost', 'webapp', 'vmJ0@DE4sH6NKp4%HD%shF7BJWSIvU', 'content');
  $resultsRecordSet = selectFromTable('content_table', 'string', $dbConnection);

  if (!empty($resultsRecordSet)) {
    echo recordsetToText($resultsRecordSet, $dbConnection);
  } else {
    echo "Failure!\n";
    echo "<p>Unable to retrieve results:</p>\n";
    echo "<p>Error Code:" . mysql_errno() . "</p>\n";
    echo "<p>Error Message:" . mysql_error() . "</p>\n";
  }
?>

